languageCode = "en-us"
title = "According to Ja-plan"
baseurl = "http://according-to-japlan.tk/"
theme = "hugo-geo"

[params]
	# Render the rotating globe in the sidebar
	showglobe = true

	# Include favicon
	favicon = "favicon.ico"

	# Email
	email = "percivalgambit@gmail.com"

	# Header Title for the main page
	header = "According to Ja-plan"

	# Sidebar profile picture
	profilepic = "img/profile.png"

	# Title/subtitle for the sidebar
	#title = ""
	subtitle = "Lee Ehudin"

	analytics = "UA-102040311-1"

	# Nav links below the profile picture
	[[params.navlinks]]
	name = "About"
	url = "about/"

	[[params.navlinks]]
	name = "Blog"
	url = "post/"
