languageCode = "en-us"
title = "According to Ja-plan"
baseurl = "http://according-to-japlan.tk/"
theme = "hugo-geo"

[params]
	# Don't render the rotating globe in the sidebar
	showglobe = false

	# Include favicon
	#favicon = "favicon.ico"

	# Email
	email = "percivalgambit@gmail.com"

	# Header Title for the main page
	header = "According to Ja-plan"

	# Sidebar profile picture
	#profilepic = ""

	# Title/subtitle for the sidebar
	#title = ""
	#subtitle = ""
